### PR TITLE
add type info and change to !=

### PR DESCRIPTION
**Pull request by diivm**

### CODE REVIEW

**Review by aPonza — APPROVED** [review]
LGTM but I usually avoid commit messages with "and", so in this case I'd have commited `is not` -> `!=` separately from the addition of `type`, and in fact the latter should probably be part of the second commit anyways (I don't know what [o/p] stands for though). You can squash commits during merge anyways :)

**Comment by kunaltyagi** [comment]
* Any reason for putting the json in git?
* What's `type_kind`?
* What's the difference in `is not` and `!=`?

**Comment by diivm** [comment]
> what [o/p] stands for

Output files commits (generated JSONs)

> Any reason for putting the json in git?

Just for the time being, including outputs for review (if needed). Will remove them later.

> What's type_kind?

The type of element. Need it for member type:
https://github.com/divmadan/pcl/blob/62bb91df43db36a77e0dddab17eaa57eee6ead1b/bindings/python/json/common/impl/point_types.json#L214-L215

> What's the difference in is not and !=?

`is not` wasn't filtering for `"Invalid"`

**Comment by diivm** [comment]
~~It's showing conflicts but the conflict is my change.~~
~~Might be something to do with [this](https://www.githubstatus.com/incidents/d60fmldlvw48). Wasn't able to make pull requests earlier today.~~

**Comment by kunaltyagi** [comment]
> > What's type_kind?
> 
> The type of element. Need it for member type:

In that case, wouldn't it be better to rename the variable as `type_of_element`?

**Pull request merged**
