### PR TITLE
[pytest.yml] update

### PR DESCRIPTION
**Pull request by diivm**
- renaming
- remove pull_request trigger
- remove commented out caching
- use env variable for path (`bindings/python`)
- enable artifacts

### CODE REVIEW

**Comment by kunaltyagi** [comment]
Commit messages are 💯

**Comment by diivm** [comment]
> Commit messages

@kunaltyagi 
All will disappear as `fix` commits

**Comment by kunaltyagi** [comment]
I'm just having fun. Saw this due to notification :)

**Comment by diivm** [comment]
Ik.
Ready for merge.

**Review by kunaltyagi — APPROVED** [review]

**Pull request merged**
